a.out: main.c board.c file.c moor.c neummann.c
	cc -ggdb main.c board.c file.c moor.c neummann.c
test_movement: test_movement.c moor.c neummann.c
	cc -ggdb test_movement.c moor.c neummann.c -o test_movement
